### ISSUE TITLE
Initialisation error - index 0 possible for lower remnant mass bin

### ISSUE THREAD

**Issue by ajw278** [stammler/dustpy#11]
**Describe the bug**
I have just downloaded the latest version of dustpy, and it is failing to initialise a disc. I have installed with Python3.10 and Python 3.11 on Mac and Ubuntu respectively. When initialising (sim.initialize()) I get the following error:

```
At line 458 of file ../dustpy/std/dust.f90
Fortran runtime error: Index '0' of dimension 1 of array 'm' below lower bound of 1
```

Tracking it down, it looks like its simply that these lines:

```
 ! Lower mass bin in which the remnant mass is distributed
      krm(j, i) = minloc(m, 1, mrm < m) - 1
      ! Fraction of remnant particle that gets distributed in the lower
      ! mass bin krm. The fraction that gets distributed into the larger
      ! mass bin krm+1 i given by 1-epsFrag
      epsFrag(j, i) = ( m( krm(j, i) + 1 ) - mrm ) / mip1_m_mi( krm(j, i) )
```

Are responsible - presumably krm can just be < 1 . I would imagine just removing the -1 would be fine, but am not sure. I do not think I am doing anything silly. 

**To Reproduce**
This is really just out of the box - literally just following the instructions the manual pages get me this. As I say, I would assume I'm doing something wrong, but I don't see how - and the error is on 2 completely different machines, with different OS and conda environments. 

**Expected behavior**
It should initialise the parameters - particularly this is in the initialisation of the coagulation parameters. 

**Software versions**
Most recent dustpy and standard gfortran compilers. I don't think this is relevant here because its just a bug in the f90 code, but happy to share specifics if needed.

**Additional context**
First time user, so really sorry if I have done something dumb!

**Comment by ajw278** [comment]
![Screenshot 2024-10-15 at 14 00 49](https://github.com/user-attachments/assets/16d92674-acad-4545-b26c-0c619dc8a495)

Update - fixed by insisting krm is at least 1, but then I get the attached initialisation - all the particles seem to be initialised to the minimum mass. Not quite sure what this is about.

**Comment by birnstiel** [comment]
is this just the default setup or are you doing anything between `sim = dustpy.Simulation()` and `sim.initialize()`?

**Comment by ajw278** [comment]
Yes, it's just the default exactly as you quote.

**Comment by stammler** [comment]
Hey @ajw278, thank you for the report!

I could reproduce the bug after changing optimization/debugging flags during compilation.

The issue is caused by a machine precision error in cases where the remnant mass is misleadingly identical to the largest mass in the grid. In this case the condition in line 454 is never true and the index in line 458 becomes out of bounds.

However, since this is a special cases that is treated separately in line 462 and following the array in question is overwritten and the overall calculation correct.

I'm not an expert in compilers, but maybe modern compilers are able to catch this and optimize it, which may be why it never happened to us previously.

Thank you for catching that! The commit 51a3bf1c531fc6e4a4800c75d21fb37f594587e5 is fixing the issue and you can install the updated version from GitHub until a new version is available on PyPI.

I was wondering since you got this runtime error, if you maybe have compiler optimization turned off and/or debugging flags turned on by default on your system. If that is the case, you may want to change that, otherwise you can run into performance issues later on.

With respect to the attached screenshot. It is not only the smallest mass bin that is filled, but a couple of mass bins as can be seen by the power law in the upper central panel. The shown screenshot is perfectly fine. This is how the default initial condition should look like.

Thanks again for this report!

**Comment by ajw278** [comment]
PS. This was when running the code, with no other changes to defaults.

**Comment by stammler** [comment]
Thank you for pointing this out.
It is a similar issue as before, where an index is out of bounds for a boundary value. But since the boundaries are treated separately, it did not affect the simulation. Commit 5ab19b667f5067ba935b87069d3b140c77a8ecab should fix the problem.

Can you check if this works for you?

Weird. I am using exactly the same `gfortran` version. But I never got any of these error or warnings before.

**Comment by ajw278** [comment]
I've been playing around. It turns out that compiler options were responsible - sorry for that. I had forgotten that I had in fact changed FFLAGS for another code, and I hadn't reset. In fact, the fix you pushed didn't fix the bug above, but It seems that an -O2 flag was responsible for the problem. I have instead used -O3, and the code now runs (seemingly) without a problem. I am also not an expert on compilers, but its interesting that these problems depend on the compiler optimisation. Might be worth an update to the install documentation for the future, but in any case thanks for all your help Sebastian and Til! 

Best,
Andrew

**Comment by stammler** [comment]
Just to clarify, which commit did not fix the bug?
We nevertheless want to try to clean up the code.

**Comment by ajw278** [comment]
The last commit ([did5ab19b6](https://github.com/stammler/dustpy/commit/5ab19b667f5067ba935b87069d3b140c77a8ecab)) not fix the bug related to the radial grid upper bound. Perhaps the easiest way is to test the code is to try changing your compilers to -O2? In fact, I have just also tried, no flag at all which interestingly seems to go back to the first bug. For the record these are a list of compiler options I have tried 

[No options] -- results in original bug re. mass bins still, even after fixes
-w -fallow-argument-mismatch -O2 -O -Wall -fcheck=all -g -fbacktrace -- after fixes, now still throws up radial bin bug
-O3 -- runs fine

Let me know if I can do anything else to help.

**Comment by stammler** [comment]
I was compiling with `-Wall -Wextra -pedantic -fcheck=all -fbacktrace -O0` and did not get any errors or warnings during compilation or runtime. And I also do not see how the code in 5ab19b667f5067ba935b87069d3b140c77a8ecab could still throw an out-of-bounds error. Is it still the identical error message with the identical line? Did the line number change?

Just to be sure, are you running a DustPy version installed from GitHub with the most recent commit and not from PyPI, which is still not updated?

`pip install git+https://github.com/stammler/dustpy`

**Comment by ajw278** [comment]
Sorry, I got this wrong, I got myself in a mess with windows and compilers, its the -O2 option that continues to make problems. So, to reproduce this problem, I did

`pip uninstall dustpy`

`export FFLAGS="-O2"`

From inside the dustpy directory (up to date):

`pip install .`

Then I run the following script: 

`from dustpy import Simulation


#del sim.integrator.instructions

sim = Simulation()
print('Initialize')
sim.initialize()

#Code fails on initialize

print('Run..')
sim.run()
`

The message I get is: 

`Initialize
At line 458 of file ../dustpy/std/dust.f90
Fortran runtime error: Index '0' of dimension 1 of array 'm' below lower bound of 1
`

Which indeed looks the same as originally. Now, if I reverse the process and do:

`pip uninstall dustpy`

`export FFLAGS="-O3"`

`pip install .`

Then run the script above again the code runs (initializes and then runs) without any bug. So I think the compiler flags can still somehow produce problem even after your earlier fixes...

**Comment by ajw278** [comment]
Ahh sorry. I had pulled the most recent version of git, but now I'm using pip with `pip install git+https://github.com/stammler/dustpy` and its fine even with the `-O2` compiler argument. I guess then I just had the wrong version sorry.

**Comment by stammler** [comment]
Okay, thank you.

But just to clarify. Are you in the most recent version?

Does `git log -1` show the hash `5ab19b667f5067ba935b87069d3b140c77a8ecab`?

Because line `458` as is shown in your error message is not a relevant line anymore?

**Comment by stammler** [comment]
Okay, thank you so much for finding this!
If you encounter any more issues, please let us know!
